### ISSUE TITLE
why there is no ReadMe file? 

### ISSUE THREAD

**Issue by AnasMK** [zd2100/PScout#5]
why there is no ReadMe file?  How can I run the tool?

**Comment by OmkarMozar** [comment]
@AnasMK Pscout 1 and Pscout 2 no longer support higher versions of android from 6.0
If  you want older results , you don't actually need to run it you can find it over [https://github.com/zyrikby/PScout](here) . If you still want to fix it for higher versions. you need to fix Pscout-1.  Pscout 2 is not stable and results are not accurate. [https://github.com/dweinstein/pscout](here) is link to pscout-1 and its official [http://pscout.csl.toronto.edu/](page)

**Comment by AnasMK** [comment]
@OmkarMozar, thank you
